name: Criar Instâncias S3

on:
  issues:
    types: [opened]

jobs:
  criar_instancias_s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v2 
      
      - name: Configuarar AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_CHAVE_ACESSO }}
          aws-secret-access-key: ${{ secrets.AWS_CHAVE_ACESSO_SECRETA }}
          aws-region: as-east-1

      - name: Extrair informações do issue
        id: issue_info
        run: |
          export BUCKET_NAME=$(echo "${{ github.event.issue.title }}")
          echo "bucket_name: $BUCKET_NAME"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Executar Terraform para criar instâncias S3
        run: |
          cd terraform
          cd instancias_s3
          terraform init
          terraform apply -auto-approve -var "bucket_name=${{ env.BUCKET_NAME }}" 

      - name: Adicionar comentário
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: "Instância S3 criada com sucesso!
          Nome do bucket: ${{ env.BUCKET_NAME }}"
