name: CRIAÇÃO DE INSTANCIAS S3

on:
  issues:
    types: [labeled]

jobs:
  criar_instancias_s3:
    if: github.event.label.name == 'Aprovado'
    runs-on: ubuntu-latest
    steps:
      - name: VERIFICANDO REPOSITORIO
        uses: actions/checkout@v2

      - name: INSTALANDO O TERRAFORM
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12.2

      - name: CONFIGURAÇÃO DO AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: sa-east-1
          aws-access-key-id: ${{ secrets.AWS_CHAVE_ACESSO }}
          aws-secret-access-key: ${{ secrets.AWS_CHAVE_ACESSO_SECRETA }}

      - name: EXTRAINDO NOME DO BUCKET DO TITULO DA ISSUE
        id: extrair_nome
        run: |
          echo PREFIXO=$(echo "${{ github.event.issue.title }}")
          SUFIXO=$(shuf -i 0000-9999 -n 1)
          BUCKET_NAME="${PREFIXO}-${SUFIXO}"
          echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV
          echo "Nome do bucket: $BUCKET_NAME"

      - name: CRIANDO INSTANCIAS S3
        run: |
          cd terraform/instancias_s3
          terraform init
          terraform apply -auto-approve -var "bucket_name=${{ env.BUCKET_NAME }}"

      - name: INSTALANDO O GITHUB CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: ADICIONANDO COMENTÁRIO NA ISSUE
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: |
            Instância S3 criada com sucesso!
            Nome do bucket: ${{ env.BUCKET_NAME }}
